# Generated by Django 2.2.26 on 2022-01-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20220128_1932"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO pay_type (name)
VALUES ('Card'),
       ('Cash');


INSERT INTO category (name,parent_id)
VALUES ('Масло',null);
INSERT INTO category (name,parent_id)
VALUES ('Моторное',1),
       ('Синтетическое',2),
       ('Минеральное',2),
       ('Полусинтетическое',2);


INSERT INTO filter (name,category_id)
VALUES ('Вязкость','1');


INSERT INTO product (name, category_id, description, image_path, price)
VALUES ('MOTUL 8100 ECO-nergy','3','Энергосберегающее 100% синтетическое моторное масло разработано специально для мощных современных бензиновых и дизельных двигателей автомобилей, в том числе с непосредственным впрыском, для которых предусмотрено использование масел с низкой высокотемпературной вязкостью в условиях высоких скоростей сдвига (HTHS). Предназначено для бензиновых и дизельных двигателей, созданных по новым технологиям, для которых предписаны масла "Fuel Economy" (ACEA A1/B1 и А5/В5). Совместимо с системами нейтрализации отработавших газов. ACEA Стандарты: ACEA A5/B5 API Стандарты: SL. Одобрения: FORD WSS M2C 913D; Jaguar, Land Rover STJLR.03.5003; Renault RN0700.','product/1.jpg','4500'),
       ('Zepro Touring','3','','product/2.jpg','4000'),
       ('Lukoil Genesis','3','','product/4.jpg','3500'),
       ('Shell HX8','3','','product/7.jpg','3400'),
       ('ZIC X9','3','','product/8.jpg','3800'),
       ('Shell HX7','3','','product/9.jpg','2950'),
       ('GM Motor oil','5','','product/10.jpg','3400'),
       ('Total Quarz INEO','3','','product/11.jpg','3400'),
       ('HYUNDAI XTeer','3','','product/12.jpg','3800'),
       ('Idemitsu','3','','product/3.jpg','2690'),
       ('Nissan','3','','product/6.jpg','3950'),
       ('Supreme','3','','product/5.jpg','2790'),
       ('Mannol Diesel','4','API CG-4/CF-4/CF/SL; ACEA E2/B3/A2','product/13.jpg','1600'),
       ('Sintec Super','4','API SG/CD','product/14.jpg','1421'),
       ('Mannol Safari','4','','product/15.jpg','1645'),
       ('OILRIGHT М-8ДМ','4','20w-20. API СD. дизельное','product/16.jpg','1361');


INSERT INTO product_filter_value (product_id, filter_id, value)
VALUES ('1','1','5w-30'),
       ('2','1','5w-30'),
       ('3','1','5w-30'),
       ('4','1','5w-40'),
       ('5','1','5w-40'),
       ('6','1','10w-40'),
       ('7','1','5w-30'),
       ('8','1','5w-30'),
       ('9','1','5w-30'),
       ('10','1','5w-40'),
       ('11','1','5w-40'),
       ('12','1','5w-30'),
       ('13 ','1','15w-40'),
       ('14','1','15w-40'),
       ('15','1','20W-50'),
       ('16','1','20w-20');
            """
        )
    ]
