# Generated by Django 2.2.26 on 2022-01-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_data"),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION public.get_children(IN _category_id integer)
    RETURNS integer[]
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
  child_list integer[];
  res integer[];
  child_id integer;
BEGIN
  select array(
    SELECT category.id
    FROM category
    WHERE category.parent_id = _category_id
  ) into child_list;
  raise notice '%', child_list;
  
  res = res || child_list || _category_id;
  
  FOREACH child_id IN ARRAY child_list
  LOOP
    res = res || get_children(child_id);
  END LOOP;
  
  return ARRAY(SELECT DISTINCT UNNEST(res) ORDER BY 1);
END;
$BODY$;
            """
        )
    ]
